[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Salmeron Océane"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
keras = "^2.6.0"
tensorflow = "2.5.0"
pandas = "^1.3.2"
opencv-python="4.3.0.36"
pylint = "^2.9.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
